global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'notifications'

receivers:
- name: 'notifications'
  slack_configs:
  - channel: '#andrey_romanchev'
  email_configs:
  - to: username@gmail.com
    from: username@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "username@gmail.com"
    auth_identity: "username@gmail.com"
    auth_password: "XXXXXX"
