version: '3.3'
services:
  post_db:
    env_file: .env
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    env_file: .env
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${APP_PORT}:${APP_PORT}/tcp
    networks:
      - front_net
    container_name: ui

  post:
    env_file: .env
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
    container_name: post

  comment:
    env_file: .env
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
    container_name: comment

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
    container_name: node-exporter

  mongodb-exporter:
    env_file: .env
    image: eses/mongodb_exporter:latest
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - back_net
    container_name: mongodb-exporter

  cloudprober-exporter:
    image: ${USERNAME}/cloudprober:latest
    networks:
      - front_net
    container_name: cloudprober-exporter


volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
