version: '3.3'
services:
  post_db:
    env_file: .env
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    env_file: .env
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${APP_PORT}:${APP_PORT}/tcp
    networks:
      - front_net
    container_name: ui

  post:
    env_file: .env
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
    container_name: post

  comment:
    env_file: .env
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
    container_name: comment

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
