version: '3.3'
services:
  post_db:
    env_file: .env
    image: mongo:${MONGO_IMAGE_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    env_file: .env
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    ports:
      - ${APP_PORT}:${APP_PORT}/tcp
    networks:
      - front_net
    container_name: ui
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    env_file: .env
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    networks:
      - back_net
      - front_net
    container_name: post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    env_file: .env
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    networks:
      - back_net
      - front_net
    container_name: comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:


networks:
  back_net:
    external:
      name: docker_back_net
  front_net:
    external:
      name: docker_front_net
